package db.model;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.With;

@With
@NoArgsConstructor
@AllArgsConstructor

public class Products {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.id
     *
     * @mbg.generated Sun Oct 02 13:45:55 IRKT 2022
     */
    private int id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.title
     *
     * @mbg.generated Sun Oct 02 13:45:55 IRKT 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.price
     *
     * @mbg.generated Sun Oct 02 13:45:55 IRKT 2022
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.category_id
     *
     * @mbg.generated Sun Oct 02 13:45:55 IRKT 2022
     */
    private int category_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.id
     *
     * @return the value of products.id
     *
     * @mbg.generated Sun Oct 02 13:45:55 IRKT 2022
     */
    public int getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.id
     *
     * @param id the value for products.id
     *
     * @mbg.generated Sun Oct 02 13:45:55 IRKT 2022
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.title
     *
     * @return the value of products.title
     *
     * @mbg.generated Sun Oct 02 13:45:55 IRKT 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.title
     *
     * @param title the value for products.title
     *
     * @mbg.generated Sun Oct 02 13:45:55 IRKT 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.price
     *
     * @return the value of products.price
     *
     * @mbg.generated Sun Oct 02 13:45:55 IRKT 2022
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.price
     *
     * @param price the value for products.price
     *
     * @mbg.generated Sun Oct 02 13:45:55 IRKT 2022
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.category_id
     *
     * @return the value of products.category_id
     *
     * @mbg.generated Sun Oct 02 13:45:55 IRKT 2022
     */
    public int getCategory_id() {
        return category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.category_id
     *
     * @param category_id the value for products.category_id
     *
     * @mbg.generated Sun Oct 02 13:45:55 IRKT 2022
     */
    public void setCategory_id(int category_id) {
        this.category_id = category_id;
    }
}